version: "3"
services:
    simsapras:
        build:
            context: .
            dockerfile: Dockerfile
        image: simsapras
        container_name: simsapras-app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./storage:/var/www/storage
            - ./.env:/var/www/.env
        networks:
            - simsapras-network
networks:
    simsapras-network:
        driver: bridge
